name: Update

on:
  schedule:
    - cron: "20 2 * * *"
  workflow_dispatch:



jobs:
  update:
    name: Update
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
      - name: Update, reformat, check, commit and push
        run: |
          nix develop --quiet --command just up

          if ! git diff --quiet; then
            nix develop --quiet --command just fmt

            bash scripts/check-lowspace.sh

            git config user.name "github-actions[bot]"
            git config user.email \
              "41898282+github-actions[bot]@users.noreply.github.com"

            git add .

            date="$(TZ=UTC date "+%FT00:00:00Z")"
            GIT_COMMITTER_DATE="$date" GIT_AUTHOR_DATE="$date" \
              git commit --message "Update dependencies"

            git push
          fi


